const DATA = [
  {"id":1,"value":6,"label":"United States"},
  {"id":2,"value":83,"label":"Sweden"},
  {"id":3,"value":31,"label":"Belarus"},
  {"id":4,"value":28,"label":"Iran"},
  {"id":5,"value":6,"label":"Philippines"},
  {"id":8,"value":46,"label":"Malaysia"},
  {"id":9,"value":34,"label":"Czech Republic"},
  {"id":11,"value":48,"label":"France"},
  {"id":14,"value":5,"label":"Moldova"},
  {"id":15,"value":33,"label":"Indonesia"},
  {"id":17,"value":33,"label":"Ukraine"},
  {"id":21,"value":7,"label":"Germany"},
  {"id":23,"value":38,"label":"Argentina"},
  {"id":25,"value":92,"label":"Peru"},
  {"id":26,"value":37,"label":"Brazil"},
  {"id":32,"value":29,"label":"Kyrgyzstan"},
  {"id":33,"value":85,"label":"Afghanistan"},
  {"id":35,"value":17,"label":"Japan"},
  {"id":36,"value":57,"label":"Indonesia"},
  {"id":37,"value":50,"label":"Nigeria"},
  {"id":39,"value":8,"label":"Tunisia"},
  {"id":41,"value":67,"label":"Armenia"},
  {"id":42,"value":92,"label":"Russia"},
  {"id":43,"value":1,"label":"Colombia"},
  {"id":45,"value":74,"label":"Vietnam"},
  {"id":48,"value":21,"label":"Poland"},
  {"id":51,"value":96,"label":"Brazil"},
  {"id":54,"value":95,"label":"Germany"},
  {"id":58,"value":41,"label":"Belarus"},
  {"id":61,"value":77,"label":"Ecuador"},
  {"id":68,"value":33,"label":"Portugal"},
  {"id":71,"value":70,"label":"Philippines"},
  {"id":74,"value":58,"label":"United States"},
  {"id":75,"value":65,"label":"Sri Lanka"},
  {"id":77,"value":74,"label":"Russia"},
  {"id":81,"value":96,"label":"Comoros"},
  {"id":82,"value":57,"label":"Greece"},
  {"id":83,"value":32,"label":"Vietnam"},
  {"id":84,"value":81,"label":"Sweden"},
  {"id":85,"value":35,"label":"Ivory Coast"},
  {"id":86,"value":49,"label":"Slovenia"},
  {"id":87,"value":63,"label":"Finland"},
  {"id":90,"value":36,"label":"Portugal"},
  {"id":91,"value":60,"label":"Macedonia"},
  {"id":93,"value":99,"label":"Netherlands"},
  {"id":97,"value":19,"label":"Croatia"},
  {"id":98,"value":28,"label":"Luxembourg"},
  {"id":99,"value":59,"label":"France"},
  {"id":100,"value":76,"label":"Marshall Islands"},
];

// Return random data from a mock data array
export function getData(size = 7) {
  return new Promise(resolve => {
    const shuffled = DATA.sort(() => 0.5 - Math.random());
    resolve(shuffled.slice(0, size));
  });
}